# Generated by Django 5.0.3 on 2024-03-09 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_juego', models.IntegerField()),
                ('nombre_juego', models.CharField(max_length=512)),
                ('año_salida', models.IntegerField()),
                ('pais_salida', models.CharField(max_length=512)),
                ('idioma_disponible', models.CharField(max_length=512)),
                ('genero', models.CharField(max_length=512)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
